version: '3'

services:

  blog-api:
    container_name: blog-api
    restart: always
    build:
      context: .
    volumes:
      - ./build/libs/:/blog
    ports:
      - "8080:8080"
    depends_on:
      - blog-mysql
    environment:
      SPRING_PROFILES_ACTIVE: development
      MYSQL_URL: jdbc:mysql://blog-mysql/blog
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  blog-mysql:
    container_name: blog-mysql
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog